markup:
  goldmark:
    renderer:
      unsafe: true

baseURL: "https://master--shimmering-elf-307184.netlify.app"
theme: "up-business-theme"
languageCode: "en-us"

title: "collegeskart"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "collegeskart"
  description: "collegeskart is your tailored guide through the maze of educational choices. We’re here to personalise your journey, from finding the right program to easing your accommodation search."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    linkedin: "https://www.linkedin.com/in/divyanshu-porwal-0456272a4"
    instagram: "https://www.instagram.com/collegeskart"
    facebook: "https://www.facebook.com/profile.php?id=61554310514853"
    twitter: "https://twitter.com/collegeskart"
    koo: "https://www.kooapp.com/profile/collegeskart"
    youtube: "https://www.youtube.com/channel/UCSMR3BRHnD-zwfHUB7JgbCg"


  location:
    - "Knowledge Park, Greater Noida, Uttar Pradesh, India 201310"

  contact:
    - "collegeskart@gmail.com"
    - "+91 8076849550"

  copyright: "© 2023 collegeskart All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About us"
      url: "/about"
      weight: 2

    - name: "Colleges"
      url: "/colleges"
      weight: 3

    - name: "Student Centre"
      url: "/student-centre"
      weight: 4

    - name: "Hostels"
      url: "/hostels"
      weight: 5

  buttons:
    - name: "Start your journey"
      url: "/#"
      weight: 4
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About us"
      url: "/about"
      weight: 2

    - name: "Colleges"
      url: "/colleges"
      weight: 3

    - name: "Student Centre"
      url: "/student-centre"
      weight: 4

    - name: "Hostels"
      url: "/hostels"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
